apiVersion: skaffold/v2beta22
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  # push: false
  # googleCloudBuild:
  #   projectId: polar-equinox-339318
  artifacts:
    - image: azeemz/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: azeemz/client
      context: client
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "**/*.js"
    - image: azeemz/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: azeemz/orders
      context: orders
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: azeemz/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: azeemz/payments
      context: payments
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
